apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 # Redis default port
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:latest

---

apiVersion: v1
kind: Service
metadata:
  name: mypod-service
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: mypod
        image: luisrivas35/my-app:latest
