apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:latest

---

apiVersion: v1
kind: Service
metadata:
  name: mypod-service
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod-deployment
spec:
  replicas: 1  # Initial number of replicas
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: mypod
        image: luisrivas35/my-app:latest

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mypod-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mypod-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization (percentage)
